[package]
name = "local_settings"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
domain = { path = "../../domain" }
