[package]
name = "plugin_hub"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
domain = { path = "../../domain" }
git2 = "0.19"
toml = "0.8.14"
serde = { version = "1.0", features = ["derive"] }
