[workspace]
members = [
    "domain",
    "driving",
    "lagrappe_back",
    "driven/datasource",
    "driven/plugin_manager",
    "driven/local_settings", "driven/plugin_hub",
]
resolver = "2"

[workspace.dependencies]
env_logger = "0.11"
log = "0.4"
